[project]
name = "scrape-roberthalf"
version = "0.1.0"
description = "Scraping tool using Playwright with proxy support"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.51.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
